# Generated by Django 5.2.11 on 2026-03-18 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.CharField(choices=[('volunteer', 'Volunteer'), ('senior', 'Senior'), ('care_home', 'Care Home')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to Say')], max_length=20, null=True)),
                ('council_area', models.CharField(blank=True, choices=[('aberdeen_city', 'Aberdeen City'), ('aberdeenshire', 'Aberdeenshire'), ('angus', 'Angus'), ('argyll_and_bute', 'Argyll and Bute'), ('clackmannanshire', 'Clackmannanshire'), ('dumfries_and_galloway', 'Dumfries and Galloway'), ('dundee_city', 'Dundee City'), ('east_ayrshire', 'East Ayrshire'), ('east_dunbartonshire', 'East Dunbartonshire'), ('east_lothian', 'East Lothian'), ('east_renfrewshire', 'East Renfrewshire'), ('city_of_edinburgh', 'City of Edinburgh'), ('falkirk', 'Falkirk'), ('fife', 'Fife'), ('glasgow_city', 'Glasgow City'), ('highland', 'Highland'), ('inverclyde', 'Inverclyde'), ('midlothian', 'Midlothian'), ('moray', 'Moray'), ('na_h-eileanan_siar_(western_isles)', 'Na h-Eileanan Siar (Western Isles)'), ('north_ayrshire', 'North Ayrshire'), ('north_lanarkshire', 'North Lanarkshire'), ('orkney', 'Orkney'), ('perth_and_kinross', 'Perth and Kinross'), ('renfrewshire', 'Renfrewshire'), ('scottish_borders', 'Scottish Borders'), ('shetland_islands', 'Shetland Islands'), ('south_ayrshire', 'South Ayrshire'), ('south_lanarkshire', 'South Lanarkshire'), ('stirling', 'Stirling'), ('west_dunbartonshire', 'West Dunbartonshire'), ('west_lothian', 'West Lothian')], max_length=255)),
                ('care_home_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('outdoor', 'Outdoor'), ('home', 'Home & Hobbies'), ('companionship', 'Companionship'), ('errand', 'Errand')], max_length=255)),
                ('activity_name', models.CharField(max_length=255)),
                ('council_area', models.CharField(choices=[('aberdeen_city', 'Aberdeen City'), ('aberdeenshire', 'Aberdeenshire'), ('angus', 'Angus'), ('argyll_and_bute', 'Argyll and Bute'), ('clackmannanshire', 'Clackmannanshire'), ('dumfries_and_galloway', 'Dumfries and Galloway'), ('dundee_city', 'Dundee City'), ('east_ayrshire', 'East Ayrshire'), ('east_dunbartonshire', 'East Dunbartonshire'), ('east_lothian', 'East Lothian'), ('east_renfrewshire', 'East Renfrewshire'), ('city_of_edinburgh', 'City of Edinburgh'), ('falkirk', 'Falkirk'), ('fife', 'Fife'), ('glasgow_city', 'Glasgow City'), ('highland', 'Highland'), ('inverclyde', 'Inverclyde'), ('midlothian', 'Midlothian'), ('moray', 'Moray'), ('na_h-eileanan_siar_(western_isles)', 'Na h-Eileanan Siar (Western Isles)'), ('north_ayrshire', 'North Ayrshire'), ('north_lanarkshire', 'North Lanarkshire'), ('orkney', 'Orkney'), ('perth_and_kinross', 'Perth and Kinross'), ('renfrewshire', 'Renfrewshire'), ('scottish_borders', 'Scottish Borders'), ('shetland_islands', 'Shetland Islands'), ('south_ayrshire', 'South Ayrshire'), ('south_lanarkshire', 'South Lanarkshire'), ('stirling', 'Stirling'), ('west_dunbartonshire', 'West Dunbartonshire'), ('west_lothian', 'West Lothian')], max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('additional_details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(default='open', max_length=20)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('relationship', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(default='pending', max_length=20)),
                ('completion_status', models.CharField(default='incomplete', max_length=20)),
                ('hidden_by_requester', models.BooleanField(default=False)),
                ('hidden_by_volunteer', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindred.activity')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_matches', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindred.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
