# Generated by Django 5.2.11 on 2026-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindred', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='council_area',
            field=models.CharField(blank=True, choices=[('aberdeen_city', 'Aberdeen City'), ('aberdeenshire', 'Aberdeenshire'), ('angus', 'Angus'), ('argyll_and_bute', 'Argyll and Bute'), ('clackmannanshire', 'Clackmannanshire'), ('dumfries_and_galloway', 'Dumfries and Galloway'), ('dundee_city', 'Dundee City'), ('east_ayrshire', 'East Ayrshire'), ('east_dunbartonshire', 'East Dunbartonshire'), ('east_lothian', 'East Lothian'), ('east_renfrewshire', 'East Renfrewshire'), ('city_of_edinburgh', 'City of Edinburgh'), ('falkirk', 'Falkirk'), ('fife', 'Fife'), ('glasgow_city', 'Glasgow City'), ('highland', 'Highland'), ('inverclyde', 'Inverclyde'), ('midlothian', 'Midlothian'), ('moray', 'Moray'), ('na_h-eileanan_siar_(western_isles)', 'Na h-Eileanan Siar (Western Isles)'), ('north_ayrshire', 'North Ayrshire'), ('north_lanarkshire', 'North Lanarkshire'), ('orkney', 'Orkney'), ('perth_and_kinross', 'Perth and Kinross'), ('renfrewshire', 'Renfrewshire'), ('scottish_borders', 'Scottish Borders'), ('shetland_islands', 'Shetland Islands'), ('south_ayrshire', 'South Ayrshire'), ('south_lanarkshire', 'South Lanarkshire'), ('stirling', 'Stirling'), ('west_dunbartonshire', 'West Dunbartonshire'), ('west_lothian', 'West Lothian')], max_length=255),
        ),
    ]
