# Generated by Django 5.2.11 on 2026-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindred', '0006_activity_status_match_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
