# Generated by Django 5.2.11 on 2026-03-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindred', '0007_alter_activity_category_alter_activity_council_area'),
        ('kindred', '0007_alter_emergencycontact_mobile'),
    ]

    operations = [
    ]
