# Generated by Django 5.2.11 on 2026-03-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindred', '0008_merge_20260318_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='gender_preference',
        ),
    ]
